export default class {
    id;
    x;
    y;
    size;
    mass;
    skin;
    badge;
    clan;
    name;
    flags;
    partyCode;
    isFood;
    cellType;
    virusType;
    extendedFlags;
    extraData;
    isVirus;
    isPellet;
    isFriend;
    isPlayer;
    isMe;
    isBot;
    isMinion;
    constructor() {
        this.id = 0;
        this.x = 0;
        this.y = 0;
        this.badge = 0;
        this.name = "";
        this.size = 0;
        this.mass = 0;
        this.skin = 0;
        this.clan = "";
        this.flags = 0;
        this.partyCode = "";
        this.cellType = 0;
        this.virusType = 0;
        this.isFood = false;
        this.extendedFlags = 0;
        this.extraData = '';
        this.isVirus = false;
        this.isPellet = false;
        this.isFriend = false;
        this.isPlayer = false;
        this.isMe = false;
        this.isBot = false;
        this.isMinion = false;
    }
}